#######################################################################
# DO NOT EDIT!  DO NOT EDIT!  DO NOT EDIT!  DO NOT EDIT!  DO NOT EDIT!
#
# This R code was parsed from RSP by the R.rsp package.
#######################################################################
# Sets the public RspPage 'page' object
page <- RspPage(pathname="index.html.rsp");
# Gets the output connection (or filename) for the response [OBSOLETE]
out <- getOutput(response);
#======================================================================
# BEGIN RSP CODE
#======================================================================
pkg <- Package("R.rsp");
toc <- read.dcf("00Index.dcf");
write(response, "\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head>\n <title>");
# <%=getName(pkg)%>
write(response, getName(pkg));
write(response, " User Guides</title>\n <link rel=\"stylesheet\" type=\"text/css\" href=\"../../R.css\">\n</head>\n<body>\n\n<h1>");
# <%=getTitle(pkg)%>
write(response, getTitle(pkg));
write(response, " <img class=\"toplogo\" src=\"../../../doc/html/logo.jpg\" alt=\"[R logo]\" width=\"101\" height=\"77\"></h1>\n<hr>\n\n<h2>User Guides and Package Vignettes</h2>\n<ul>\n");
for (ii in seq(length=nrow(toc))) {
files <- trim(unlist(strsplit(toc[ii,"Files"], split=",", fixed=TRUE)));
exts <- toupper(gsub(".*[.]([^.]*)$", "\\1", files));
names(files) <- exts;
write(response, " <li>\n <strong>");
# <%=toc[ii,"Title"]%>
write(response, toc[ii,"Title"]);
write(response, "</strong> - ");
# <%=toc[ii,"Description"]%>
write(response, toc[ii,"Description"]);
write(response, "\n");
for (type in names(files)) {
write(response, "   [<a href=\"");
# <%=files[type]%>
write(response, files[type]);
write(response, "\">");
# <%=type%>
write(response, type);
write(response, "</a>]\n");
}
write(response, " </li>\n");
}
write(response, "</ul>\n<br>\n\n<hr>\n<div align=\"center\"><a href=\"../html/00Index.html\">[Package Contents]</a></div>\n<br>\n<div align=\"center\"><small>This page was generated by the <a href=\"http://cran.r-project.org/web/packages/R.rsp/\">R.rsp</a> package.</small></div>\n\n</body>\n</html>\n");
#======================================================================
# END RSP CODE
#======================================================================
